export const CUSTOM_PRESET_ID = 'custom';

export type CommunityPresetRegion = 'europe' | 'north_america' | 'oceania' | 'other';

export interface CommunityMqttPreset {
  id: string;
  region: CommunityPresetRegion;
  brokerHost: string;
  brokerPort: number;
  transport: 'websockets' | 'tcp';
  useTls: boolean;
  authMode: 'token' | 'none' | 'password';
  tokenAudience?: string;
  websocketPath?: string;
  username?: string;
  password?: string;
  iata?: string;
  pubkeyUsername?: boolean;
  requiresTopicTemplate?: boolean;
  hasEmbeddedCredentials?: boolean;
  needsBackendSubstitution?: boolean;
}

const MESHCORE_TOPIC = 'meshcore/{IATA}/{PUBLIC_KEY}/packets';

// Parsed from the Dutch-MeshCore MQTTPresets.h list (36 upstream + bsmesh).
// Scheme → transport/tls: wss = websockets+tls, mqtts = tcp+tls, mqtt = tcp.
// auth_type → auth_mode: JWT = token (+audience), NONE = none, USERPASS = password.
export const COMMUNITY_MQTT_PRESETS: readonly CommunityMqttPreset[] = [
  {
    id: 'analyzer-us',
    region: 'north_america',
    brokerHost: 'mqtt-us-v1.letsmesh.net',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqtt-us-v1.letsmesh.net',
    websocketPath: '/mqtt',
  },
  {
    id: 'analyzer-eu',
    region: 'europe',
    brokerHost: 'mqtt-eu-v1.letsmesh.net',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqtt-eu-v1.letsmesh.net',
    websocketPath: '/mqtt',
  },
  {
    id: 'nz-analyzer',
    region: 'oceania',
    brokerHost: 'meshcore-mqtt-1.baird.io',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'meshcore-mqtt-1.baird.io',
    websocketPath: '/',
  },
  {
    id: 'meshmapper',
    region: 'other',
    brokerHost: 'mqtt.meshmapper.net',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqtt.meshmapper.net',
    websocketPath: '/mqtt',
  },
  {
    id: 'meshrank',
    region: 'other',
    brokerHost: 'meshrank.net',
    brokerPort: 8883,
    transport: 'tcp',
    useTls: true,
    authMode: 'none',
    iata: 'XYZ',
    requiresTopicTemplate: true,
  },
  {
    id: 'waev',
    region: 'other',
    brokerHost: 'mqtt.waev.app',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqtt.waev.app',
    websocketPath: '/mqtt',
  },
  {
    id: 'meshomatic',
    region: 'north_america',
    brokerHost: 'us-east.meshomatic.net',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'us-east.meshomatic.net',
    websocketPath: '/mqtt',
  },
  {
    id: 'cascadiamesh',
    region: 'north_america',
    brokerHost: 'mqtt-v1.cascadiamesh.org',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqtt-v1.cascadiamesh.org',
    websocketPath: '/mqtt',
  },
  {
    id: 'tennmesh',
    region: 'north_america',
    brokerHost: 'mqtt.tennmesh.com',
    brokerPort: 1883,
    transport: 'tcp',
    useTls: false,
    authMode: 'password',
    username: 'mqttfeed',
    password: 'tc2live',
    hasEmbeddedCredentials: true,
  },
  {
    id: 'nashmesh',
    region: 'north_america',
    brokerHost: 'mqtt.nashme.sh',
    brokerPort: 1883,
    transport: 'tcp',
    useTls: false,
    authMode: 'password',
    username: 'meshdev',
    password: 'large4cats',
    hasEmbeddedCredentials: true,
  },
  {
    id: 'ctmesh',
    region: 'north_america',
    brokerHost: 'mqtt.ctmesh.org',
    brokerPort: 1883,
    transport: 'tcp',
    useTls: false,
    authMode: 'password',
    username: 'meshdev',
    password: 'large4cats',
    hasEmbeddedCredentials: true,
  },
  {
    id: 'chimesh',
    region: 'north_america',
    brokerHost: 'mqtt.chimesh.org',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqtt.chimesh.org',
    websocketPath: '/',
  },
  {
    id: 'meshat.se',
    region: 'europe',
    brokerHost: 'meshcore-mqtt.meshat.se',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'meshcore-mqtt.meshat.se',
    websocketPath: '/',
  },
  {
    id: 'eastidahomesh',
    region: 'north_america',
    brokerHost: 'live.eastidahomesh.com',
    brokerPort: 1883,
    transport: 'tcp',
    useTls: false,
    authMode: 'none',
  },
  {
    id: 'coloradomesh',
    region: 'north_america',
    brokerHost: 'mqtt.meshcore.coloradomesh.org',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqtt.meshcore.coloradomesh.org',
    websocketPath: '/',
  },
  {
    id: 'dutchmeshcore-1',
    region: 'europe',
    brokerHost: 'collector1.dutchmeshcore.nl',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'collector1.dutchmeshcore.nl',
    websocketPath: '/mqtt',
  },
  {
    id: 'dutchmeshcore-2',
    region: 'europe',
    brokerHost: 'collector2.dutchmeshcore.nl',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'collector2.dutchmeshcore.nl',
    websocketPath: '/mqtt',
  },
  {
    id: 'meshcore-analyzer-eu',
    region: 'europe',
    brokerHost: 'mqtt.meshcore-analyzer.eu',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqtt.meshcore-analyzer.eu',
    websocketPath: '/',
  },
  {
    id: 'meshcore-ca-1',
    region: 'north_america',
    brokerHost: 'mqtt1.meshcore.ca',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqtt1.meshcore.ca',
    websocketPath: '/mqtt',
  },
  {
    id: 'meshcore-ca-2',
    region: 'north_america',
    brokerHost: 'mqtt2.meshcore.ca',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqtt2.meshcore.ca',
    websocketPath: '/mqtt',
  },
  {
    id: 'meshcore-fi',
    region: 'europe',
    brokerHost: 'mc-mqtt.meshcore.fi',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mc-mqtt.meshcore.fi',
    websocketPath: '/',
  },
  {
    id: 'okimesh-1',
    region: 'north_america',
    brokerHost: 'mqtt1.okimesh.org',
    brokerPort: 9002,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqtt1.okimesh.org',
    websocketPath: '/mqtt',
  },
  {
    id: 'okimesh-2',
    region: 'north_america',
    brokerHost: 'mqtt2.okimesh.org',
    brokerPort: 9002,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqtt2.okimesh.org',
    websocketPath: '/mqtt',
  },
  {
    id: 'inwmesh',
    region: 'other',
    brokerHost: 'scope.inwmesh.org',
    brokerPort: 8883,
    transport: 'tcp',
    useTls: true,
    authMode: 'password',
  },
  {
    id: 'bostonmesh',
    region: 'north_america',
    brokerHost: 'mqttmc01.bostonme.sh',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqttmc01.bostonme.sh',
    websocketPath: '/mqtt',
  },
  {
    id: 'rflab',
    region: 'other',
    brokerHost: 'mqtt.rflab.io',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqtt.rflab.io',
    websocketPath: '/',
  },
  {
    id: 'ipnt.uk',
    region: 'europe',
    brokerHost: 'mqtt.ipnt.uk',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqtt.ipnt.uk',
    websocketPath: '/',
  },
  {
    id: 'flmesh',
    region: 'north_america',
    brokerHost: 'mcmqtt.jntconnections.com',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mcmqtt.jntconnections.com',
    websocketPath: '/',
  },
  {
    id: 'corecomms',
    region: 'other',
    brokerHost: 'mqtt.corecomms.net',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqtt.corecomms.net',
    websocketPath: '/mqtt',
  },
  {
    id: 'meshtexas',
    region: 'north_america',
    brokerHost: 'mqtt.meshtexas.org',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqtt.meshtexas.org',
    websocketPath: '/mqtt',
  },
  {
    id: 'mesh-chaun14',
    region: 'europe',
    brokerHost: 'mqtt.mesh.chaun14.fr',
    brokerPort: 1884,
    transport: 'tcp',
    useTls: false,
    authMode: 'password',
    username: '{pubkey}',
    pubkeyUsername: true,
    needsBackendSubstitution: true,
  },
  {
    id: 'wcmesh',
    region: 'north_america',
    brokerHost: 'mqtt.wcmesh.com',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqtt.wcmesh.com',
    websocketPath: '/',
  },
  {
    id: 'atvirastinklas',
    region: 'europe',
    brokerHost: 'mqtt-mc.atvirastinklas.lt',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqtt-mc.atvirastinklas.lt',
    websocketPath: '/',
  },
  {
    id: 'gomesh',
    region: 'other',
    brokerHost: 'mqtt.gomesh.dev',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqtt.gomesh.dev',
    websocketPath: '/',
  },
  {
    id: 'idahomesh',
    region: 'north_america',
    brokerHost: 'mqtt.idahomesh.org',
    brokerPort: 443,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqtt.idahomesh.org',
    websocketPath: '/mqtt',
  },
  {
    id: 'ntxmesh',
    region: 'north_america',
    brokerHost: 'ntxmesh.dhovin.me',
    brokerPort: 8883,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'ntxmesh.dhovin.me',
    websocketPath: '/',
  },
  {
    id: 'bsmesh',
    region: 'europe',
    brokerHost: 'mqtt.bsmesh.de',
    brokerPort: 8885,
    transport: 'websockets',
    useTls: true,
    authMode: 'token',
    tokenAudience: 'mqtt.bsmesh.de',
    websocketPath: '/',
  },
];

export const REGION_ORDER: readonly CommunityPresetRegion[] = [
  'europe',
  'north_america',
  'oceania',
  'other',
];

export function applyPresetToConfig(
  config: Record<string, unknown>,
  preset: CommunityMqttPreset
): Record<string, unknown> {
  return {
    ...config,
    broker_host: preset.brokerHost,
    broker_port: preset.brokerPort,
    transport: preset.transport,
    use_tls: preset.useTls,
    tls_verify: true,
    auth_mode: preset.authMode,
    iata: preset.iata ?? (config.iata as string | undefined) ?? '',
    token_audience: preset.authMode === 'token' ? (preset.tokenAudience ?? preset.brokerHost) : '',
    websocket_path: preset.transport === 'websockets' ? (preset.websocketPath ?? '/') : '/',
    username: preset.authMode === 'password' ? (preset.username ?? '') : '',
    password: preset.authMode === 'password' ? (preset.password ?? '') : '',
    topic_template: preset.requiresTopicTemplate
      ? ''
      : (config.topic_template as string | undefined) || MESHCORE_TOPIC,
  };
}

export function detectPresetId(config: Record<string, unknown>): string {
  const host = String(config.broker_host ?? '');
  const port = Number(config.broker_port);
  const match = COMMUNITY_MQTT_PRESETS.find(
    (p) =>
      p.brokerHost === host &&
      p.brokerPort === port &&
      p.transport === ((config.transport as string) || 'websockets') &&
      p.authMode === ((config.auth_mode as string) || 'token')
  );
  return match ? match.id : CUSTOM_PRESET_ID;
}
